#include <stdio.h>

#define NAME_LENGTH 30
#define PAR_LIMIT 10
#define LOCALS_GLOBALS_LIMIT 30
#define TYPE_LENGTH 30
#define INHERITED_LIMIT 50
#define METHOD_LIMIT 10
#define CLASS_LIMIT 20
#define FIND 1
#define NOT_FIND 0
#define CLASS 0
#define INTERFACE 1
#define INIT_INT 0
#define INIT_DOUBLE 1
#define INIT_CHAR 2
#define INIT_INT_EXPR 3
#define INIT_DOUBLE_EXPR 4
#define INIT_CHAR_EXPR 5
#define EXPRESSION 6
#define INIT_OBJECT 7
#define INIT_OBJECT_EXPR 8
#define INIT_ARRAY 9
#define STRUCT_WORD 10
#define IF_WORD 11
#define ELIF_WORD 12
#define ELSE_WORD 13
#define WHILE_WORD 14
#define FOR_WORD 15
#define SWITCH_WORD 16
#define CASE_WORD 17
#define DEFAULT_WORD 18
#define BREAK_WORD 19
#define RETURN_WORD 20
#define PRINT_WORD 21
#define INPUT_WORD 22
#define CALL_WORD 23
#define OPEN_BRACE 30
#define CLOSE_BRACE 31
#define OPEN_PAR 32
#define CLOSE_PAR 33
#define CLOSE_PAR_AND_SEMICOLON 34
#define OPEN_BRACKET 35
#define CLOSE_BRACKET 36
#define CLOSE_PAR_EXPR 37
#define COMMA 40
#define APOSTROPHE 41
#define OR  42
#define AND 43
#define NOT 44
#define NOTEQUAL 45
#define CONSTRUCTOR 50
#define VOID_METHOD 51
#define INT_METHOD 52
#define DOUBLE_METHOD 53
#define CHAR_METHOD 54
#define DECLARED 60
#define UNDECLARED 61
#define CASE_ID 62
#define CASE_DIGIT 63
#define CASE_CHAR 64
#define LOCAL 65
#define PAR 66
#define GLOBAL 67
#define INH 68
#define ID 70
#define DIGIT 71
#define DOUBLE 72
#define CHAR 73
#define COMMA_ID 74
#define COMMA_DOUBLE 75
#define COMMA_DIGIT 76
#define NEW 77
#define SUPER 78
